config/routes.rb
Rails.application.routes.draw do
  resources :rental_records
  resources :vehicles
  resources :customers
  
  mount RailsAdmin::Engine => 'admin', as: 'rails_admin'
  namespace :admin do
    resources :users
    root to: "users#index"
  end
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/rental_record.rb
class RentalRecord < ActiveRecord::Base
  belongs_to :customer
  belongs_to :vehicle
end

app/controllers/rental_records_controller.rb
class RentalRecordsController < ApplicationController
  before_action :set_rental_record, only: [:show, :edit, :update, :destroy]

  # GET /rental_records
  # GET /rental_records.json
  def index
    #@rental_records = RentalRecord.paginate(:page => params[:page], :per_page => 10).order('id DESC')
    @rental_records = RentalRecord.all
  end

  # GET /rental_records/1
  # GET /rental_records/1.json
  def show
  end

  # GET /rental_records/new
  def new
    @rental_record = RentalRecord.new
  end

  # GET /rental_records/1/edit
  def edit
  end

  # POST /rental_records
  # POST /rental_records.json
  def create
    @rental_record = RentalRecord.new(rental_record_params)

    respond_to do |format|
      if @rental_record.save
        format.html { redirect_to @rental_record, notice: 'Rental record was successfully created.' }
        format.json { render :show, status: :created, location: @rental_record }
      else
        format.html { render :new }
        format.json { render json: @rental_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rental_records/1
  # PATCH/PUT /rental_records/1.json
  def update
    respond_to do |format|
      if @rental_record.update(rental_record_params)
        format.html { redirect_to @rental_record, notice: 'Rental record was successfully updated.' }
        format.json { render :show, status: :ok, location: @rental_record }
      else
        format.html { render :edit }
        format.json { render json: @rental_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rental_records/1
  # DELETE /rental_records/1.json
  def destroy
    @rental_record.destroy
    respond_to do |format|
      format.html { redirect_to rental_records_url, notice: 'Rental record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rental_record
      @rental_record = RentalRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rental_record_params
      params.require(:rental_record).permit(:customer_id, :vehicle_id, :start_date, :end_date, :lastUpdated, :output)
    end
end

app/helpers/rental_records_helper.rb
module RentalRecordsHelper
end

app/views/rental_records/_form.html - Copy,sigpad.erb
<%= simple_form_for(@rental_record) do |f| %>
  <%= f.error_notification %>


  <div class="form-inputs">
    <%= f.association :customer %>
    <%= f.association :vehicle %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.input :lastUpdated %>
  </div>

  
   <div class="sigPad">
    <label for="name">Print your name</label>
    <input type="text" name="name1" id="name1" class="name1">
    <p class="typeItDesc">Review your signature</p>
    <p class="drawItDesc">Draw your signature</p>
       <ul class="sigNav">
           <li class="drawIt"><a href="#draw-it" >Draw It</a></li>
          <li class="clearButton"><a href="#clear">Clear</a></li>
        </ul>
    <div class="sig sigWrapper">
      <div class="typed"></div>
      <canvas class="pad" width="498" height="155"></canvas>
      <input type="hidden" name="output" class="output">
    </div>
    </div>
 
 
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/rental_records/_form.html - Copy,sigpad2.erb
<%= simple_form_for(@rental_record) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :customer %>
    <%= f.association :vehicle %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.input :lastUpdated %>
  </div>

    
   <div class="sigPad">
     <p class="drawItDesc">Draw your signature</p>
       <ul class="sigNav">
          <li class="clearButton"><a href="#clear">Clear</a></li>
        </ul>
    <div class="sig sigWrapper">
      <div class="typed"></div>
      <canvas class="pad" width="498" height="155"></canvas>
      <%= f.input_field :output, as: :hidden %>
    </div>
    </div>


 
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/rental_records/_form.html 2016-05-06_12.02.19.erb
<%= simple_form_for(@rental_record) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :customer %>
    <%= f.association :vehicle %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.input :lastUpdated %>
  </div>

<style>
.sigPad {
  margin: 0;
  padding: 0;
  width: 303px; /* Change the width */
}

.sigWrapper {
  clear: both;
  height: 108px; /* Change the height */

  border: 1px solid #ccc;
}
</style>  

    <div class="sigPad">
     <p class="drawItDesc">Draw your signature</p>
       <ul class="sigNav">
          <li class="clearButton"><a href="#clear">Clear</a></li>
        </ul>
    <div class="sig sigWrapper">
     <div class="typed"></div>
       <canvas class="pad" width="300" height="105"></canvas>
      <%= f.input :output , as: :hidden , input_html: { class: 'output' } %>
    </div>
    </div>
  <div>
    <br>
  </div>
    
    
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/rental_records/_form.html.erb
<%= simple_form_for(@rental_record) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :customer %>
    <%= f.association :vehicle %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.input :lastUpdated %>
  </div>

  
<style>
.sigPad {
  margin: 0;
  padding: 0;
  width: 303px; /* Change the width */
}

.sigWrapper {
  clear: both;
  height: 108px; /* Change the height */

  border: 1px solid #ccc;
}
</style>  

    <div class="sigPad">
     <p class="drawItDesc">Draw your signature</p>
       <ul class="sigNav">
          <li class="clearButton"><a href="#clear">Clear</a></li>
        </ul>
    <div class="sig sigWrapper">
     <div class="typed"></div>
       <canvas class="pad" width="300" height="105"></canvas>
      <%= f.input :output , as: :hidden , input_html: { class: 'output' } %>
    </div>
    </div>
  <div>
    <br>
  </div>
    
    
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/rental_records/edit.html.erb
<div class="page-header">
  <%= link_to rental_records_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @rental_record, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing rental_record</h1>
</div>

<%= render 'form' %>

app/views/rental_records/index.html 2016-05-06_10.46.59.erb
<div class="page-header">
  <%= link_to new_rental_record_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Rental record
  <% end %>
  <h1>Listing rental_records</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th></th>
        <th></th>
       <!-- disable destroy.. 
         <th></th>
        -->
            <th>Customer</th>
            <th>Vehicle</th>
            <th>Start date</th>
            <th>End date</th>
            <th>Lastupdated</th>
            <th>Output</th>
          </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @rental_records) do |rental_record| %>
        <td><%= link_to 'Show', rental_record %></td>
        <td><%= link_to 'Edit', edit_rental_record_path(rental_record) %></td>
        <!-- disable destroy.. 
        <td><%= link_to 'Destroy', rental_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        -->
            <td><%= rental_record.customer %></td>
            <td><%= rental_record.vehicle %></td>
            <td><%= rental_record.start_date %></td>
            <td><%= rental_record.end_date %></td>
            <td><%= rental_record.lastUpdated %></td>
            <td><%= rental_record.output %></td>
          <% end %>
    </tbody>
  </table>
</div>

app/views/rental_records/index.html 2016-05-06_12.02.01.erb
<div class="page-header">
  <%= link_to new_rental_record_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Rental record
  <% end %>
  <h1>Listing rental_records</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th></th>
        <th></th>
       <!-- disable destroy.. 
         <th></th>
        -->
            <th>Customer</th>
            <th>Vehicle</th>
            <th>Start date</th>
            <th>End date</th>
          </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @rental_records) do |rental_record| %>
        <td><%= link_to 'Show', rental_record %></td>
        <td><%= link_to 'Edit', edit_rental_record_path(rental_record) %></td>
        <!-- disable destroy.. 
        <td><%= link_to 'Destroy', rental_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        -->
            <td><%= rental_record.customer %></td>
            <td><%= rental_record.vehicle %></td>
            <td><%= rental_record.start_date %></td>
            <td><%= rental_record.end_date %></td>
          <% end %>
    </tbody>
  </table>
</div>

app/views/rental_records/index.html.erb
<div class="page-header">
  <%= link_to new_rental_record_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Rental record
  <% end %>
  <h1>Listing rental_records</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">

  

  
  <thead>
      <tr>
        <th></th>
        <th></th>
       <!-- disable destroy.. 
         <th></th>
        -->
            <th>Customer</th>
            <th>Vehicle</th>
            <th>Start date</th>
            <th>End date</th>
          </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @rental_records) do |rental_record| %>
        <td><%= link_to 'Show', rental_record %></td>
        <td><%= link_to 'Edit', edit_rental_record_path(rental_record) %></td>
        <!-- disable destroy.. 
        <td><%= link_to 'Destroy', rental_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        -->
            <td><%=  rental_record.customer.name
            %></td>
            <td><%= rental_record.vehicle %></td>
            <td><%= rental_record.start_date %></td>
            <td><%= rental_record.end_date %></td>
          <% end %>
    </tbody>
  </table>
</div>

app/views/rental_records/new.html.erb
<div class="page-header">
  <%= link_to rental_records_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New rental_record</h1>
</div>

<%= render 'form' %>

app/views/rental_records/show.html.erb
<div class="page-header">
  <%= link_to rental_records_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_rental_record_path(@rental_record), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show rental_record</h1>
</div>

<dl class="dl-horizontal">
  <dt>Customer:</dt>
  <dd><%= @rental_record.customer %></dd>

  <dt>Vehicle:</dt>
  <dd><%= @rental_record.vehicle %></dd>

  <dt>Start date:</dt>
  <dd><%= @rental_record.start_date %></dd>

  <dt>End date:</dt>
  <dd><%= @rental_record.end_date %></dd>

  <dt>Lastupdated:</dt>
  <dd><%= @rental_record.lastUpdated %></dd>

  <dt>Output:</dt>
  <dd><%= @rental_record.output %></dd>

</dl>