config/routes.rb
Rails.application.routes.draw do
  resources :rental_records
  resources :vehicles
  resources :customers
  
  mount RailsAdmin::Engine => 'admin', as: 'rails_admin'
  namespace :admin do
    resources :users
    root to: "users#index"
  end
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/customer.rb
class Customer < ActiveRecord::Base
   
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :address, :phone, :discount)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= simple_form_for(@customer) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone %>
    <%= f.input :discount %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<div class="page-header">
  <%= link_to customers_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @customer, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing customer</h1>
</div>

<%= render 'form' %>

app/views/customers/index.html.erb
<div class="page-header">
  <%= link_to new_customer_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Customer
  <% end %>
  <h1>Listing customers</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th></th>
        <th></th>
       <!-- disable destroy.. 
         <th></th>
        -->
            <th>Name</th>
            <th>Address</th>
            <th>Phone</th>
            <th>Discount</th>
          </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @customers) do |customer| %>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <!-- disable destroy.. 
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        -->
            <td><%= customer.name %></td>
            <td><%= customer.address %></td>
            <td><%= customer.phone %></td>
            <td><%= customer.discount %></td>
          <% end %>
    </tbody>
  </table>
</div>

app/views/customers/new.html.erb
<div class="page-header">
  <%= link_to customers_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New customer</h1>
</div>

<%= render 'form' %>

app/views/customers/show.html.erb
<div class="page-header">
  <%= link_to customers_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_customer_path(@customer), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show customer</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @customer.name %></dd>

  <dt>Address:</dt>
  <dd><%= @customer.address %></dd>

  <dt>Phone:</dt>
  <dd><%= @customer.phone %></dd>

  <dt>Discount:</dt>
  <dd><%= @customer.discount %></dd>

</dl>