config/routes.rb
Rails.application.routes.draw do
  resources :rental_records
  resources :vehicles
  resources :customers
  
  mount RailsAdmin::Engine => 'admin', as: 'rails_admin'
  namespace :admin do
    resources :users
    root to: "users#index"
  end
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:veh_reg_no, :category, :brand, :name, :photo, :daily_rate)
    end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html 2016-05-06_12.55.48.erb
<%= simple_form_for(@vehicle) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :veh_reg_no %>
    <%= f.input :category %>
    <%= f.input :brand %>
    <%= f.input :name %>
    <%= f.input :photo %>
    <%= f.input :daily_rate %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/vehicles/_form.html.erb
<%= simple_form_for(@vehicle) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :veh_reg_no %>
    <%= f.input :category %>
    <%= f.input :brand %>
    <%= f.input :name %>
    <%= f.input :daily_rate %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<div class="page-header">
  <%= link_to vehicles_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @vehicle, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing vehicle</h1>
</div>

<%= render 'form' %>

app/views/vehicles/index.html.erb
<div class="page-header">
  <%= link_to new_vehicle_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Vehicle
  <% end %>
  <h1>Listing vehicles</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th></th>
        <th></th>
       <!-- disable destroy.. 
         <th></th>
        -->
            <th>Veh reg no</th>
            <th>Category</th>
            <th>Brand</th>
            <th>Name</th>
            <th>Photo</th>
            <th>Daily rate</th>
          </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @vehicles) do |vehicle| %>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <!-- disable destroy.. 
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        -->
            <td><%= vehicle.veh_reg_no %></td>
            <td><%= vehicle.category %></td>
            <td><%= vehicle.brand %></td>
            <td><%= vehicle.name %></td>
            <td><%= vehicle.photo %></td>
            <td><%= vehicle.daily_rate %></td>
          <% end %>
    </tbody>
  </table>
</div>

app/views/vehicles/new.html.erb
<div class="page-header">
  <%= link_to vehicles_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New vehicle</h1>
</div>

<%= render 'form' %>

app/views/vehicles/show.html.erb
<div class="page-header">
  <%= link_to vehicles_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_vehicle_path(@vehicle), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show vehicle</h1>
</div>

<dl class="dl-horizontal">
  <dt>Veh reg no:</dt>
  <dd><%= @vehicle.veh_reg_no %></dd>

  <dt>Category:</dt>
  <dd><%= @vehicle.category %></dd>

  <dt>Brand:</dt>
  <dd><%= @vehicle.brand %></dd>

  <dt>Name:</dt>
  <dd><%= @vehicle.name %></dd>

  <dt>Photo:</dt>
  <dd><%= @vehicle.photo %></dd>

  <dt>Daily rate:</dt>
  <dd><%= @vehicle.daily_rate %></dd>

</dl>